version: "3"
services:
  wp-db:
    image: "postgres"

    container_name: "emt_events"

    environment:
      - POSTGRES_USER=emt
      - POSTGRES_PASSWORD=emt123
      - POSTGRES_DB=events

    ports:
      - "5432:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data