create table country
(
    id        bigint generated by default as identity primary key,
    name      varchar(255),
    continent varchar(255)
);

create table author
(
    id         bigint generated by default as identity primary key,
    name       varchar(255),
    surname    varchar(255),
    country_id bigint references country
);

create table book
(
    id              bigint generated by default as identity primary key,
    name            varchar(255),
    description     varchar(4000),
    category        varchar(50),
    author_id       bigint references author,
    availableCopies integer,
    deleted         boolean default false
);

create table wish_list
(
    id              bigint generated by default as identity primary key,
    book_user_id    varchar(255) references book_users(username),
    books_id        bigint references book
);

create table book_users
(
    username                   varchar(255) primary key,
    password                   varchar(255),
    name                       varchar(255),
    surname                    varchar(255),
    wishlist_id                bigint references wishlist,
    is_account_non_expired     boolean default true,
    is_account_non_locked      boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled                 boolean default true,
    role                       varchar(50)
);

create table user_book
(
    id              bigint generated by default as identity primary key,
    user_id         varchar(255) references book_users(username),
    book_id         bigint references book
);

create index idx_user_username_password on book_users (username, password);
create index idx_user_username on book_users (username);
create index idx_user_role on book_users (role);
